# Generated by Django 4.2.19 on 2026-03-10 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='superhero',
            name='alter_egos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='api_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='base',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 10, 17, 27, 44, 185034, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='first_appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superhero',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superhero',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superhero',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='alignment',
            field=models.CharField(choices=[('good', 'Hero'), ('bad', 'Villain'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='combat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='durability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image_url',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superhero',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superhero',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
